server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:file:./data/testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  #    url: jdbc:postgresql://localhost:5432/lottery
  #    username: postgres
  #    password: postgres

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: true
    locations: classpath:/db/migration

  jpa:
    hibernate:
      ddl-auto: none
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true


# Default global values
app:
  default:
    draw-duration: 60
    max-pool-size: 3