DROP TABLE IF EXISTS LotteryType CASCADE;
DROP TYPE draw_status;
DROP TABLE IF EXISTS Draw CASCADE;
DROP TABLE IF EXISTS DrawResult CASCADE;
DROP TABLE IF EXISTS Customers CASCADE;
DROP TYPE customer_type;
DROP TABLE IF EXISTS Ticket CASCADE;
DROP TABLE IF EXISTS Invoice CASCADE;
DROP TABLE IF EXISTS Payment CASCADE;
