-- Таблица предсозданных билетов
CREATE TABLE PreGeneratedTickets
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draw_id      BIGINT      NOT NULL,
    numbers      JSON        NOT NULL,
    numbers_hash VARCHAR(64) NOT NULL,
    issued       BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_draw FOREIGN KEY (draw_id) REFERENCES Draw (id) ON DELETE CASCADE
);

-- Индекс для уникальной комбинации в рамках тиража
CREATE UNIQUE INDEX idx_pre_generated_ticket_draw_hash ON PreGeneratedTickets (draw_id, numbers_hash);