-- Создаем таблицу предсозданных билетов
CREATE TABLE IF NOT EXISTS PreGeneratedTickets
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    draw_id BIGINT  NOT NULL,
    numbers JSON   NOT NULL,
    issued  BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_draw FOREIGN KEY (draw_id) REFERENCES Draw (id) ON DELETE CASCADE
);
